### ISSUE TITLE
Client 1 quit with exit code 2 and signal 0

### ISSUE THREAD

**Issue by mkuratczyk** [sourcegraph/cody.nvim#1] opened 2023-05-18 15:18 UTC
Hi,

I've just installed this plugin but so far no luck making it work.
After the installation, it accept the ToC and the CLI is downloaded successfully.

However, when I try `:CodyChat`, I just get `Client 1 quit with exit code 2 and signal 0`

When I true `:CodyDiff`, I get `Cody is thinking...` but that's it.

Is there some log I can check? Some debugging steps?

I'm using neovim 0.9.0 on macOS

Thanks,

**Comment by mrnugget** [comment] 2023-05-31 18:06
Hey @mkuratczyk! I assume you have a sourcegraph.com access token, set the url, configured codebase etc, like this?

```lua
require("cody").setup {
  url = "https://sourcegraph.com",
  accessToken = "TOKEN",
  repos = {"github.com/sourcegraph/sourcegraph"}, -- or repo of your choosing
}
```

You can also find the location of where `llmsp` should be installed like this (in Neovim): `:lua print(vim.fn.stdpath("data"))`

That should give you a folder in which you can find `llmsp`.

Can you run it like this?

```shell-session
$ ./llmsp-v0.1.0-beta.1-arm64-darwin --help
Usage of ./llmsp-v0.1.0-beta.1-arm64-darwin:
  -auto-complete string
        Enable auto-completion (off, init, always)
  -stdio
        Stdio mode (default true)
  -token string
        LLM provider token
  -url string
        LLM provider URL
```

Also check out how to debug LSP stuff in Neovim: https://github.com/neovim/nvim-lspconfig#troubleshooting

There might be something in the logs

**Comment by mkuratczyk** [comment] 2023-05-31 19:10
I found this in the lsp log:
```
[START][2023-05-31 21:08:17] LSP logging initiated
[WARN][2023-05-31 21:08:17] .../lua/vim/lsp.lua:1637    "buf_attach_client called on unloaded buffer (id: 1): "
[WARN][2023-05-31 21:08:17] ...lsp/handlers.lua:537     "LLMSP initialized!"
[ERROR][2023-05-31 21:08:27] .../vim/lsp/rpc.lua:734    "rpc"   "/Users/mkuratczyk/.local/share/nvim/llmsp/llmsp-v0.1.0-beta.1-arm64-darwin"   "stderr"        'panic: Post ".api/graphql": unsupported protocol scheme ""\n\ngoroutine 29 [running]:\ngithub.com/pjlast/llmsp/providers.(*SourcegraphLLM).ExecuteCommand(0x140000b6000, {0x102767e48?, 0x1400011a000}, {{0x14000019008, 0x11}, {'
[ERROR][2023-05-31 21:08:27] .../vim/lsp/rpc.lua:734    "rpc"   "/Users/mkuratczyk/.local/share/nvim/llmsp/llmsp-v0.1.0-beta.1-arm64-darwin"   "stderr"        "0x14000070ac0, 0x2, 0x4}, {0x0, 0x0}}, ...)\n\t/Users/pjlast/workspace/llmsp/providers/sourcegraph.go:594 +0x1fbc\ngithub.com/pjlast/llmsp/lsp.(*server).workspaceExecuteCommand(0x1400017a000, {0x102767e48, 0x1400011a000}, 0x1400017e000, 0x140001bf568?, {{0x14000019008, 0x11}, {0x14000070ac0, 0x2, 0x4}, ...})\n\t/Users/pjlast/workspace/llmsp/lsp/lsp.go:271 +0x2e8\ngithub.com/pjlast/llmsp/lsp.requiresInitialized[...].func1(0x40?, 0x1026ff580?, {{0x14000019008?, 0x11?}, {0x14000070ac0, 0x2, 0x4}, {0x0, 0x0}})\n\t/Users/pjlast/workspace/llmsp/lsp/lsp.go:105 +0x60\ngithub.com/pjlast/llmsp/lsp.LSPHandlerFunc[...].func1(0x0, 0x14000126600)\n\t/Users/pjlast/workspace/llmsp/lsp/lsp.go:30 +0xdc\ngithub.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0x14000112ee0, {0x102767e48, 0x1400011a000}, 0x1400017e000, 0x14000126600)\n\t/Users/pjlast/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x4c\ngithub.com/pjlast/llmsp/lsp.HandlerFunc.Handle(0x102718ce0?, {0x102767e48?, 0x1400011a000?}, 0x18?, 0x0?)\n\t/Users/pjlast/workspace/llmsp/lsp/router.go:17 +0x3c\ngithub.com/pjlast/llmsp/lsp.(*Router).Handle(...)\n\t/Users/pjlast/workspace/llmsp/lsp/router.go:"
[ERROR][2023-05-31 21:08:27] .../vim/lsp/rpc.lua:734    "rpc"   "/Users/mkuratczyk/.local/share/nvim/llmsp/llmsp-v0.1.0-beta.1-arm64-darwin"   "stderr"        "42\ngithub.com/pjlast/llmsp/lsp.(*server).Handle(0x0?, {0x102767e48, 0x1400011a000}, 0x0?, 0x14000126600)\n\t/Users/pjlast/workspace/llmsp/lsp/lsp.go:94 +0x74\ncreated by github.com/sourcegraph/jsonrpc2.asyncHandler.Handle\n\t/Users/pjlast/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/async.go:16 +0xdc\n"
```

I can call the `llsmp` binary just fine:

```
> ~/.local/share/nvim/llmsp/llmsp-v0.1.0-beta.1-arm64-darwin --help
Usage of /Users/mkuratczyk/.local/share/nvim/llmsp/llmsp-v0.1.0-beta.1-arm64-darwin:
  -auto-complete string
        Enable auto-completion (off, init, always)
  -stdio
        Stdio mode (default true)
  -token string
        LLM provider token
  -url string
        LLM provider URL
```

Note, I'm running neovim 0.9.1 now (previously 0.9.0).

**Comment by thenbe** [comment] 2023-06-01 02:32
It seems both this repo and llmsp have been transferred recently, but the code is yet to be updated to reflect this.

| Old | New |
|--------|--------|
| pjlast/llmsp | sourcegraph/llmsp |
| pjlast/cody.nvim | sourcegraph/cody.nvim | 

I'm not sure if this is the root cause of this issue (since github could very well be redirecting to the new repo name), but the following fixes it:

1. Install `llmsp` manually.
	a. `git clone https://github.com/sourcegraph/llmsp`
	b. `cd llmsp && go install`
	c. verify installation with `llmsp --help`
3. Set `dev` to true in cody's setup function. This will make the plugin [use](https://github.com/sourcegraph/cody.nvim/blob/a0ad92d1f8f0e8648adee67af6bf32c121cd3626/lua/cody/init.lua#L56) the binary you just installed.

```lua
require("cody").setup {
  dev = true, <-- 👈
  accessToken = "TOKEN",
  -- ...
}
```

**Comment by mkuratczyk** [comment] 2023-06-01 06:20
Yup, it works installed this way. Thanks!

**Comment by mrnugget** [comment] 2023-06-01 07:54
Thank you @thenbe!

**Comment by pjlast** [comment] 2023-06-05 08:04
Thanks @thenbe for the workaround

I've updated the main plugin to pull the binary from the migrated URLs and not the old URLs, and it should work without the `dev = true` workaround now 👍

**Closed as completed by pjlast** 2023-06-05 08:04 UTC
